users:
  mirass:
    current_rank:
    staff_rank:
    build_rank:
    current_title:
    titles:
      title_1: true
      title_2: false
  robnoo02:
    current_rank:
    staff_rank:
    build_rank:
    current_title:
    titles:
      title_1: true
      title_2: false