users:
  mirass:
    current_rank: manager
    staff_rank: manager
    build_rank: stone
    current_title: first_ranked
  robnoo02:
    current_rank: dev
    staff_rank: dev
    build_rank: stone
    current_title: old_player

titles:
  - first_ranked
  - build_comp
  - old_playerv