name: RankTitleString
version: 2.1
description: Creates and updates title-rank prefixes for chat
author: Mirass
main: io.github.c9lul12btw.RankTitleString
depend: [PlaceholderAPI]

commands:
  rank:
    description: 'Example command'
    usage: '/<command>'