users:
  mirass:
    current_rank: manager
    staff_rank: manager
    build_rank: master
    current_title: build_comp
    titles:
      first_ranked: true
      build_comp: true
      old_player: false
  robnoo02:
    current_rank:
    staff_rank:
    build_rank:
    current_title:
    titles:
      title_1: true
      title_2: false