name: RankTitleString
version: 2.0
description: Creates and updates title-rank prefixes for chat
author: Mirass
main: io.github.c9lul12btw.RankTitleString
depend: [PlaceholderAPI]

commands:
  rt:
    description: 'Example command'
    usage: '/<command>'